eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    config:
      token: discovery-server
  config:
    import: optional:http://localhost:8888/