spring:
  application:
    name:
      ms1
  config:
    import: optional:configserver:http://localhost:8888/
cloud:
  config:
    token:
      vault
    uri:
      http://localhost:8888/
server:
  port:
    8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone:
        http://localhost:8761/eureka




