spring:
  application:
    name:
      ms2
  config:
    import: optional:configserver:http://localhost:8888/
cloud:
  config:
    token:
      vault
server:
  port:
    7070

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone:
        http://localhost:8761/eureka




